

class ApplicationError(Exception):
    pass

class RetryOperation(Exception):
    pass